export const featuredProducts = [
    {
        id: 1,
        name: "Pakistani Chaunsa Mango",
        slug: "pakistani-chaunsa-mango",
        image: "/products/chaunsa-mango.png",
        oldPrice: 7.50,
        newPrice: 6.30,
        unit: "4 KG",
        badge: "20% OFF",
        rating: 5,
        inStock: true,
    },
    {
        id: 2,
        name: "Fresh Jamun",
        slug: "fresh-jamun",
        image: "/products/jamun.png",
        oldPrice: 3.50,
        newPrice: 3.00,
        unit: "1 KG",
        badge: "NEW",
        rating: 5,
        inStock: true,
    },
    // {
    //     id: 3,
    //     name: "Fresh Apple",
    //     image: "/products/apple.png",
    //     oldPrice: 1.50,
    //     newPrice: 1.20,
    //     badge: "HOT",
    //     rating: 5,
    // },
    // {
    //     id: 4,
    //     name: "Banana",
    //     image: "/products/banana.png",
    //     oldPrice: 1.20,
    //     newPrice: 0.95,
    //     badge: "SALE",
    //     rating: 5,
    // },
];